// $$(".reader-container p").map (p => p.innerText)

const armSents = {
    1:{
        1:"Մայքը արթնանում է ամեն առավոտ ժամը վեցին",
        2:"Նա նախաճաշ է պատրաստում և սուրճ խմում",
        3:"Նա աշխատանքի է գնում իր մեքենայով",
        4:"Նրա աշխատանքը սկսվում է առավոտյան յոթն անց երեսունին",
        5:"Մայքը ռեստորանում խոհարար է",
        6:"Նա կերակուր է պատրաստում քաղցած հաճախորդների համար",
        7:"Հաճախորդները շատ տարբեր երկրներից են",
        8:"Նրանք խոսում են շատ տարբեր լեզուներով",
        9:"Մայքը կարող է բազմաթիվ ընկերասեր մարդկանց հանդիպել",
        10:"Մայքը երջանիկ է, երբ խոսում է հաճախորդների հետ",
    },
    2:[
        "Դաստինը ոգևորված է ձմեռային արձակուրդի համար",
        "Ձմռանը նա որոշ ազատ ժամանակ ունի",
        "Նա երկու շաբաթ կարող է չաշխատել",
        "Նա ուզում է արձակուրդ գնալ",
        "Բայց նա չգիտի ուր գնալ",
        "Նա ցանկանում է մեկնել Ֆրանսիա",
        "Բայց Ֆրանսիան թանկ է",
        "Ինքնաթիռի տոմսերը թանկ են",
        "Եվ Դաստինը ֆրանսերեն չի խոսում",
        "Նա որոշում է սովորել, գումար խնայել և մնալ տանը",
    ],
    3:[
        "Կարինը ձանձրանում է աշխատավայրում և տանը",
        "Նա ամեն օր նույն բանն է անում",
        "Նա նոր հոբբի է ուզում",
        "Նախ նա փորձում է կերակուր պատրաստել",
        "Բայց նրա պատրաստածը համեղ չէ",
        "Հետո նա փորձում է լողալ",
        "Բայց նա վախենում է ջրից",
        "Կարինը տան ճանապարհին կենդանիների խանութ է տեսնում",
        "Կենդանիների խանութում նա կատու է տեսնում",
        "Կարինը գնում է կատվին, և այժմ շատ ուրախ է",
    ],
    4:[
        "Աղջիկս ամեն օր դպրոց է գնում",
        "Նրան շատ է դուր գալիս դպրոցը",
        "Նա լավ աշակերտ է",
        "Ուսուցիչները շատ են սիրում աղջկաս",
        "Աղջիկս նաև շատ ընկերներ ունի",
        "Նրա լավագույն ընկերը Էմին է",
        "Էմին սիրում է մաթեմատիկա և գիտություն",
        "Աղջիկս սիրում է անգլերեն և պատմություն",
        "Նրանք միմյանց օգնում են տնային աշխատանքները կատարել",
        "Նրանք ջանք են գործադրում և դպրոցում լավ են սովորում",
    ],
    5:[
        "Ջոնը ավագ դպրոցի աշակերտ է",
        "Նա շատ տնային առաջադրանքներ ունի",
        "Քլերը համալսարանի ուսանող է",
        "Նա նույնպես շատ տնային առաջադրանքներ ունի",
        "Ջոնը չի սիրում տնային աշխատանքը",
        "Նա սիրում է համակարգչային խաղեր խաղալ",
        "Քլերը սիրում է կարդալ և գրել",
        "Նա ամեն օր կատարում է իր տնային աշխատանքը",
        "Քլերը Ջոնի ավագ քույրն է",
        "Նա միշտ ստիպում է նրան կատարել տնային առաջադրանքները",
    ],
    6:[
        "Գիշերը Ջեյնը և Ֆրեդը հոգնած են լինում",
        "Նրանք ժամը յոթին միասին ընթրում են",
        "Նրանց որդին ընթրում է իրենց հետ",
        "Նրանք միասին հանգստանում են և հեռուստացույց դիտում",
        "Նրանց որդին նույնպես հեռուստացույց է դիտում",
        "Նրանք որդուն քնեցնում են ժամը ութին",
        "Ջեյնը տաք լոգանք է ընդունում",
        "Ֆրեդը ցնցուղ է ընդունում և լվանում է ատամները",
        "Ջեյնը գիրք է կարդում և քնում է",
        "Ֆրեդը նույնպես շուտ քուն է մտնում",
    ],
    7:[
        "Ջեյմսը աշխատում է գրասենյակում",
        "Նա ամեն օր շատ զբաղված է",
        "Նա շատ հանդիպումներ է ունենում իր հաճախորդների հետ",
        "Ջեյմսին դուր չեն գալիս այս հանդիպումները",
        "Նա կարծում է, որ դրանք շատ ձանձրալի են",
        "Որոշ հաճախորդներ բարյացակամ են նրա նկատմամբ",
        "Բայց որոշ հաճախորդներ հաճելի չեն",
        "Ջեյմսը երկար ընդմիջում է անում",
        "Նա կարող է տուն գնալ ժամը հինգին",
        "Նա ամեն օր սպասում է ժամը հինգին",
    ],
    8:[
        "Լիզան ցանկանում է գնել նոր կոշիկներ",
        "Նա գնում է կոշիկի խանութ",
        "Այնտեղ շատ գեղեցիկ կոշիկներ կան",
        "Լիզան մի զույգ կապույտ կոշիկ է փորձում",
        "Կապույտ կոշիկները շատ նեղ են",
        "Նա փորձում է սև կոշիկները",
        "Այս կոշիկները շատ հարմարավետ են",
        "Լիզան հարցնում է, թե որքան արժեն սև կոշիկները",
        "Սև կոշիկները չորս հարյուր հիսուն դոլար են",
        "Լիզան տխուր վայր է դնում կոշիկները և հեռանում",
    ],
    9: [
        "Էնդին նոր ընկերուհի ունի",
        "Նրա ընկերուհու անունը Սառա է",
        "Էնդին ցանկանում է ճաշ պատրաստել Սառայի համար",
        "Նա գնում է մթերային խանութ",
        "Էնդին զամբյուղ ու սայլակ է վերցնում",
        "Նա անցնում է բանջարեղենի բաժնով",
        "Նա նայում է սառցարանի ձկներին",
        "Նա կանգնած է աղցանների վաճառասեղանի մոտ",
        "Վերջապես նա դուրս է գալիս խանութից",
        "Էնդին գնում է տուն և պիցցա պատվիրում",
    ]
};

const engSents = {
    1:{
        1:"Mike wakes up at six o'clock every morning",
        2:"She cooks breakfast and drinks coffee",
        3:"He goes to work in his car",
        4:"His work starts at seven thirty in the morning",
        5:"Mike is a chef at a restaurant",
        6:"She cooks food for hungry customers",
        7:"Customers are from many different countries",
        8:"They speak many different languages",
        9:"Mike can meet a lot of friendly people",
        10:"Mike is happy when he's talking to customers",
    },
    2:[
        "Dustin is excited for winter break",
        "He has some free time in the winter",
        "He may not work for two weeks",
        "He wants to go on vacation",
        "But he doesn't know where to go",
        "He wants to go to France",
        "But France is expensive",
        "Plane tickets are expensive",
        "And Dustin doesn't speak French",
        "He decides to study, save money and stay at home",
    ],
    3:[
        "Karin is bored at work and at home",
        "He does the same thing every day",
        "He wants a new hobby",
        "First he tries to cook",
        "But what he cooks is not tasty",
        "Then he tries to swim",
        "But he's afraid of water",
        "Karin sees a pet store on her way home",
        "She sees a cat in the pet store",
        "Karin buys the cat and is very happy now",
    ],
    4:[
        "My daughter goes to school every day",
        "He really likes school",
        "He is a good student",
        "Teachers love my daughter very much",
        "My daughter also has many friends",
        "His best friend is Amy",
        "Amy likes math and science",
        "My daughter likes English and history",
        "They help each other with homework",
        "They work hard and do well in school",
    ],
    5:[
        "John is a high school student",
        "She has a lot of homework",
        "Claire is a university student",
        "He has a lot of homework too",
        "John doesn't like homework",
        "He likes to play computer games",
        "Claire likes to read and write",
        "He does his homework every day",
        "Claire is John's older sister",
        "She always makes him do his homework",
    ],
    6:[
        "Jane and Fred are tired at night",
        "They have dinner together at seven o'clock",
        "Their son is having dinner with them",
        "They relax and watch TV together",
        "Their son also watches TV",
        "They put their son to sleep at eight o'clock",
        "Jane takes a hot bath",
        "Fred takes a shower and brushes his teeth",
        "Jane is reading a book and falling asleep",
        "Fred goes to sleep early too",
    ],
    7:[
        "James works in the office",
        "He's very busy every day",
        "He has a lot of meetings with his clients",
        "James doesn't like these matches",
        "He thinks they're too boring",
        "Some customers are kind to him",
        "But some customers are not nice",
        "James takes a long break",
        "He can go home at five o'clock",
        "He waits for five o'clock every day",
    ],
    8:[
        "Lisa wants to buy new shoes",
        "She goes to the shoe store",
        "There are very nice shoes there",
        "Lisa is trying on a pair of blue shoes",
        "The blue shoes are too narrow",
        "She's trying on black shoes",
        "These shoes are very comfortable",
        "Lisa asks how much black shoes cost",
        "Black shoes are four hundred and fifty dollars",
        "Lisa sadly puts down her shoes and leaves",
    ],
    9:[
        "Andy has a new girlfriend",
        "His girlfriend's name is Sarah",
        "Andy wants to cook for Sarah",
        "She's going to the grocery store",
        "Andy takes a basket and a cart",
        "He's going through the vegetable section",
        "He's looking at the fish in the freezer",
        "He's standing at the salad bar",
        "Finally, he's coming out of the store",
        "Andy goes home and orders a pizza",
    ]
}